### ISSUE TITLE
Competition decrease mortality for a lot of species. Is it only because of Spain?

### ISSUE THREAD

**Issue by kunstler** [kunstler/FUNDIV_sAPROPOS#39]
It took me some time to realise what the figures were showing but for a lot of species mortality decrease when competition increase.
See for instance

![selection_020](https://user-images.githubusercontent.com/4505188/35340177-57954442-011a-11e8-90ad-983333eb93a2.png)

![selection_021](https://user-images.githubusercontent.com/4505188/35340238-77c5b044-011a-11e8-997f-6df2b6f6aa45.png)

 This is not the classical expectation (and for growth we have a strong negative effect) so I think this should be checked carefully.

Some points to check

- [ ] There is a strong interaction between climate and competition can this reverse the pattern.

- [X] Spain seems to drive a lot this pattern, I need to check if this is it still the same without Spain and discuss that with Paloma

=> Without Spain the negative effect of BATOT on mortality is much lover

**Comment by kunstler** [comment]
Two reference analysing mortality in function of BATOT with the Spanish NFI found a positive effect on mortality

- Ruiz-Benito, P. et al. 2013. Patterns and Drivers of Tree Mortality in Iberian Forests: Climatic Effects Are Modified by Competition. - PloS one 8: e56843.

- Carnicer, J. et al. 2011. Widespread crown condition decline, food web disruption, and amplified tree mortality with increased climate change-type drought. - Proceedings of the National Academy of Sciences 108: 1474–1478.

See for instance this figure from Paloma paper:
![selection_026](https://user-images.githubusercontent.com/4505188/35501539-2cf29422-04d2-11e8-8a61-6b8143bccaf7.png)
![selection_023](https://user-images.githubusercontent.com/4505188/35501544-2f5ec14a-04d2-11e8-89b0-c8cc7ca43efc.png)

The pattern I get when I plot the data per bin is quite different for *Pinus pinea* and for *Pinus pinaster* :

![selection_024](https://user-images.githubusercontent.com/4505188/35501587-4cfbe37c-04d2-11e8-8ba8-60cc1e6ea4d9.png)
![selection_025](https://user-images.githubusercontent.com/4505188/35501592-4f79b1ce-04d2-11e8-90f4-94fad14abe50.png)

So I probably did something wrong somewhere ... and the mortality value are quite different ...

I need to : 
- [ ] check the code producing those figures for errors
- [ ] re-run without managed plots (we were only excluding plot where at least one tree was harvested but with other management indications)
- [ ] run the analysis with BATOT of larger trees

**Comment by sophiathirza** [comment]
I don't think that you have the details on management in all the plots (only the French ones). I have added a csv (FunDivEUROPE_plot_management.csv) of all plots with management1 (management recorded in the first survey) and management2 (management recorded in the second survey). This includes the French plots.

The file includes all the plots that I have in the database (including the non-permanent plots), so there are plots that are in the sAPROPOS 'plot' table.

**Comment by kunstler** [comment]
@sophiathirza what is meaning of the code 0 to 9 and V in magement2 ?

What should I remove ? all plots with something else than 0 in date 1 or 2 ? There is some NA as well not a pb?

**Comment by sophiathirza** [comment]
V is a mistake - there were 'NAV' in the field and I thought that I had removed them, but I only removed the 'NA'. I corrected the heading names as well. I have put an updated csv on dropbox.

For Finland the number indicates the number of years since logging, where 1 is the current season. I had forgotten that we still had the years in the field.

NA indicates no information on management, so should be set to 0

Yes, remove all plots with anything other than 0 (or NA) in management2. I will check my notes on the Swedish inventory.. because they had lots of management information and we might be very restrictive if we exclude all plots with evidence of management in the second inventory.

**Comment by sophiathirza** [comment]
For the Swedish plots, 1 indicates any type of logging or tree cutting within the previous 25 years. Management activity dates are grouped:
* previous season
* 2 years ago
* 3-5 years ago
* 6-10 years ago
* 11-25 years ago

**Comment by kunstler** [comment]
Without managed plots the pattern is still the same see figure below 
![selection_027](https://user-images.githubusercontent.com/4505188/35682034-43cf534c-0757-11e8-8b78-00a20fb948b7.png)
![selection_028](https://user-images.githubusercontent.com/4505188/35682046-4c15fc4a-0757-11e8-96b1-4e887713526d.png)

The mortality values are however much lower. So this is probably a good idea to remove those plots as management can increase mortality rate of non harvested trees.

**Comment by kunstler** [comment]
Checking the computation of `BATOTcomp`

@sophiathirza I'm not sure what I did is perfect. To compute the basal area of competitor for a tree I did `BATOT_ha1 - ba_ha1` (thus the basal are of the other tree than the target tree). But this value has some few negative values and when I sum ba_ha1 per plot this is not equal to BATOT_ha1 ...

What do you think is wrong?

This is in the function `read_FUNDIV_tree_data`.

**Comment by sophiathirza** [comment]
I don't think that ba_ha1 and ba_ha2 are correct in the plot table. I have just checked a couple and they are not the same (as you say above).

We should recalculate the basal area of each plot. I checked my R script for the calculation and I can't see how there is a mistake. But certainly the number are not the same.

**Comment by sophiathirza** [comment]
I had ba_ha1 including only ingrowth and surviving trees and ba_ha2 only surviving and dead trees. I'd corrected the code but clearly not rerun it.

So it explains why those plots with high mortality had a low ba_ha1. I am sorry not to have seen that. It explains why the pattern of increasing mortality within increasing basal area is apparent in the climate bins - as I calculated the basal area from the trees in the climate bin rather than the plot basal area.

**Comment by kunstler** [comment]
Great !!!!! That solving this problem I have been struggling with that for days. This also explains why the pattern of decrease of mortality with BATOT was so clear (I'm more use to a messy pattern in the NFI DATA).

To check what was computed in plot file I recomputed BATOT with only surviving and ingrowth tree and this exactly what you did:
![badvsbadbatot](https://user-images.githubusercontent.com/4505188/35701698-20f26f72-0797-11e8-9f90-da0b62500944.png)
This quite different from the total basal area of all trees
![goodvsbadbatot](https://user-images.githubusercontent.com/4505188/35701723-372923da-0797-11e8-97e0-52fdfcde9f94.png)

I will re-run all survival analysis with that.
